// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.MyDbContext;

#nullable disable

namespace Services.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_II.Entities.Cita", b =>
                {
                    b.Property<int>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitaId"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<int>("TipoCitaId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CitaId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TipoCitaId");

                    b.HasIndex("UserId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Proyecto_II.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Nombre = "ADMIN"
                        },
                        new
                        {
                            RoleId = 2,
                            Nombre = "USER"
                        });
                });

            modelBuilder.Entity("Proyecto_II.Entities.Sucursal", b =>
                {
                    b.Property<int>("SucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SucursalId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SucursalId");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            SucursalId = 1,
                            Nombre = "Clinica Santa Cruz"
                        },
                        new
                        {
                            SucursalId = 2,
                            Nombre = "Clinica Nicoya"
                        },
                        new
                        {
                            SucursalId = 3,
                            Nombre = "Clinica Libera"
                        });
                });

            modelBuilder.Entity("Proyecto_II.Entities.TipoCita", b =>
                {
                    b.Property<int>("TipoCitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoCitaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoCitaId");

                    b.ToTable("TiposCita");

                    b.HasData(
                        new
                        {
                            TipoCitaId = 1,
                            Nombre = "Medicina General"
                        },
                        new
                        {
                            TipoCitaId = 2,
                            Nombre = "Odontología"
                        },
                        new
                        {
                            TipoCitaId = 3,
                            Nombre = "Pediatría"
                        },
                        new
                        {
                            TipoCitaId = 4,
                            Nombre = "Neurología"
                        });
                });

            modelBuilder.Entity("Proyecto_II.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Proyecto_II.Entities.Cita", b =>
                {
                    b.HasOne("Proyecto_II.Entities.Sucursal", "Sucursal")
                        .WithMany("Citas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_II.Entities.TipoCita", "TipoCita")
                        .WithMany("Citas")
                        .HasForeignKey("TipoCitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_II.Entities.User", "User")
                        .WithMany("Citas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("TipoCita");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proyecto_II.Entities.User", b =>
                {
                    b.HasOne("Proyecto_II.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Proyecto_II.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Proyecto_II.Entities.Sucursal", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Proyecto_II.Entities.TipoCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Proyecto_II.Entities.User", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
